// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: scan.proto

package scanpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScanRequest contains file information for scanning
type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`     // SHA256 hash of the file
	Filepath      string                 `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"` // Path to the file (relative to mounted volume)
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"` // Original filename
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ScanRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *ScanRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// ScanResponse returns scan results
type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "clean", "infected", "error"
	Results       []*ScanResult          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScanResponse) GetResults() []*ScanResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ScanResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ScanResult contains results from individual AV engines
type ScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engine        string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`       // "clamav", "comodo"
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`       // "clean", "infected"
	Detection     string                 `protobuf:"bytes,3,opt,name=detection,proto3" json:"detection,omitempty"` // Malware name if detected
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`     // Additional details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{2}
}

func (x *ScanResult) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *ScanResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScanResult) GetDetection() string {
	if x != nil {
		return x.Detection
	}
	return ""
}

func (x *ScanResult) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_scan_proto protoreflect.FileDescriptor

const file_scan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"scan.proto\x12\x04scan\"]\n" +
	"\vScanRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x1a\n" +
	"\bfilepath\x18\x02 \x01(\tR\bfilepath\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\"w\n" +
	"\fScanResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12*\n" +
	"\aresults\x18\x02 \x03(\v2\x10.scan.ScanResultR\aresults\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"t\n" +
	"\n" +
	"ScanResult\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tdetection\x18\x03 \x01(\tR\tdetection\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails2<\n" +
	"\vScanService\x12-\n" +
	"\x04Scan\x12\x11.scan.ScanRequest\x1a\x12.scan.ScanResponseB\n" +
	"Z\b.;scanpbb\x06proto3"

var (
	file_scan_proto_rawDescOnce sync.Once
	file_scan_proto_rawDescData []byte
)

func file_scan_proto_rawDescGZIP() []byte {
	file_scan_proto_rawDescOnce.Do(func() {
		file_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)))
	})
	return file_scan_proto_rawDescData
}

var file_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_scan_proto_goTypes = []any{
	(*ScanRequest)(nil),  // 0: scan.ScanRequest
	(*ScanResponse)(nil), // 1: scan.ScanResponse
	(*ScanResult)(nil),   // 2: scan.ScanResult
}
var file_scan_proto_depIdxs = []int32{
	2, // 0: scan.ScanResponse.results:type_name -> scan.ScanResult
	0, // 1: scan.ScanService.Scan:input_type -> scan.ScanRequest
	1, // 2: scan.ScanService.Scan:output_type -> scan.ScanResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scan_proto_init() }
func file_scan_proto_init() {
	if File_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scan_proto_goTypes,
		DependencyIndexes: file_scan_proto_depIdxs,
		MessageInfos:      file_scan_proto_msgTypes,
	}.Build()
	File_scan_proto = out.File
	file_scan_proto_goTypes = nil
	file_scan_proto_depIdxs = nil
}
