# syntax=docker/dockerfile:1
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo \
    -o /app/gateway-service ./gateway-service/

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/gateway-service .
EXPOSE 4000
CMD ["./gateway-service"]
